##############################################################################
#  Copyright Christopher Kormanyos 2021 - 2022.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: real-time-cpp
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  msvc-msbuild-arm:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        suite: [ am335x ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: cache win toolchains
        id: cache-toolchains
        uses: actions/cache@v3
        with:
          path: toolchains
          key: ${{ runner.os }}-toolchains
      - name: clone-real-time-cpp-toolchains-master
        if: steps.cache-toolchains.outputs.cache-hit != 'true'
        run: |
          echo Cloning GNU/GCC toolchains
          git clone -b master --depth 1 https://github.com/ckormanyos/real-time-cpp-toolchains.git ${{runner.workspace}}/toolchains
        working-directory: ./
      - name: extract-real-time-cpp-toolchain
        run: |
          echo empty for now
