name: real-time-cpp
on: [push,pull_request]
jobs:
  target-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: '[skip ci];[ci skip];[CI SKIP];[SKIP CI];***CI SKIP***;***SKIP CI***'
      - name: update-tools
        run: sudo apt install g++-10
      - name: build-target-x86_64-w64-mingw32
        run: ./target/build/build.sh x86_64-w64-mingw32 rebuild
        working-directory: ./ref_app/
        shell: bash
  target-avr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: '[skip ci];[ci skip];[CI SKIP];[SKIP CI];***CI SKIP***;***SKIP CI***'
      - name: update-tools
        run: sudo apt install gcc-avr avr-libc
      - name: build-target-avr
        run: ./target/build/build.sh avr rebuild
        working-directory: ./ref_app/
        shell: bash
