##############################################################################
#  Copyright Christopher Kormanyos 2021 - 2022.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

#        example: [ chapter02_03, chapter02_03a, chapter03_02, chapter04_04, chapter04_04a, chapter06_01, chapter06_14, chapter09_07, chapter09_08, chapter10_08, chapter10_08a, chapter11_07, chapter12_04, chapter17_03, chapter17_03a ]

name: real-time-cpp
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-avr-win-batch-examples:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        example: [ chapter02_03 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: cache-win-toolchains
        id: cache-win-toolchains
        uses: actions/cache@v3
        env:
          cache-name: cache-win-toolchains
        with:
          path: win-toolchains
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: clone-real-time-cpp-toolchains-master
        if: steps.cache-win-toolchains.outputs.cache-hit != 'true'
        run: |
          echo Cloning GNU/GCC toolchains
          git clone -b master --depth 1 https://github.com/ckormanyos/real-time-cpp-toolchains.git win-toolchains
        working-directory: ./
      - name: extract-real-time-cpp-toolchain
        run: |
          echo Moving GNU/GCC toolchain
          echo empty at the moment

