name: real-time-cpp
on: [push]
jobs:
  target-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: update-tools
        run: sudo apt install g++-10
      - name: build-target-x86_64
        run: ./build/build.sh x86_64-w64-mingw32 rebuild
        working-directory: ../ref_app/target
