##############################################################################
#  Copyright Christopher Kormanyos 2022.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: real-time-cpp-cache
on:
  push:
    branches:
      - master
jobs:
  create-cache-win-toolchains:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: cache-win-toolchains
        id: cache-win-toolchains
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}\win-toolchains
          key: ${{ runner.os }}-win-toolchains
      - name: clone-real-time-cpp-toolchains-master
        if: steps.cache-win-toolchains.outputs.cache-hit != 'true'
        run: |
          echo Cloning GNU/GCC toolchains
          git clone -b master --depth 1 https://github.com/ckormanyos/real-time-cpp-toolchains.git ${{ runner.workspace }}/win-toolchains
        working-directory: ./
      - name: verify-win-toolchains
        run: |
          echo Verify the non-moved GNU/GCC win-toolchains
          dir ${{ runner.workspace }}\win-toolchains
