##############################################################################
#  Copyright Christopher Kormanyos 2021 - 2022.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: real-time-cpp
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-msvc-example16_08:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        example: [ chapter16_08 ]
    steps:
      - uses: actions/checkout@v3
      - name: clone-boost-develop
        working-directory: ${{runner.workspace}}
        run: |
          git clone -b develop --depth 1 https://github.com/boostorg/boost.git ${{runner.workspace}}/boost-root
      - name: clone-submods
        working-directory: ${{runner.workspace}}/boost-root
        run: |
          git submodule update --init tools
          git submodule update --init libs/config
          git submodule update --init libs/math
          git submodule update --init libs/multiprecision
      - name: bootstrap-boost
        working-directory: ${{runner.workspace}}/boost-root
        run: |
          ./bootstrap.bat
          ./b2 headers
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - name: target-msvc-example16_08
        shell: cmd
        working-directory: ./
        run: |
          cd examples/${{ matrix.example }}
          set INCLUDE=${{runner.workspace}}\real-time-cpp\examples\${{ matrix.example }}\src\mcal\win32;%INCLUDE%
          set INCLUDE=${{runner.workspace}}\real-time-cpp\examples\${{ matrix.example }}\src;%INCLUDE%
          set INCLUDE=${{runner.workspace}}\boost-root;%INCLUDE%
          MSBuild -m ${{ matrix.example }}.sln -p:useenv=true -p:Configuration=Release -p:Platform=x64 /t:Rebuild
          dir .\Release\${{ matrix.example }}.exe
