name: real-time-cpp
on: [push]
jobs:
  target-x86_64:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[CI SKIP]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install g++-10
      - name: build-target-x86_64-w64-mingw32
        run: ./target/build/build.sh x86_64-w64-mingw32 rebuild
        working-directory: ./ref_app/
        shell: bash
  target-avr:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[CI SKIP]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install gcc-avr avr-libc
      - name: build-target-avr
        run: ./target/build/build.sh avr rebuild
        working-directory: ./ref_app/
        shell: bash
  target-stm32f446:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[CI SKIP]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install gcc-arm-none-eabi
      - name: build-target-stm32f446
        run: ./target/build/build.sh stm32f446 rebuild
        working-directory: ./ref_app/
        shell: bash
