##############################################################################
#  Copyright Christopher Kormanyos 2021 - 2022.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: real-time-cpp
on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: '45 23 * * *' # run at 11:45 PM UTC
jobs:
  target-avr-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [ avr, atmega2560 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: clone-osx-cross-homebrew-avr-and-install
        run: |
          echo Install avr-gcc on MacOS via osx-cross/homebrew-avr
          git clone -b main --depth 1 https://github.com/osx-cross/homebrew-avr.git ../homebrew-avr-root
          cd ../homebrew-avr-root
          brew tap osx-cross/avr
          brew install avr-gcc@11
        working-directory: ./
      - name: target-avr-macos-${{ matrix.suite }}
        run: |
          echo Install make via brew
          brew install make
          echo query the GNUmake version
          gmake --version
          echo Add avr-gcc@11 path
          PATH="/usr/local/opt/avr-gcc@11/bin:$PATH"
          echo query the avr-gcc version
          avr-g++ -v
          echo Manually call GNUmake to build the target
          gmake -f target/app/make/app_make_linux.gmk rebuild TGT=${{ matrix.suite }} MY_GMAKE=gmake
          ls -la ./bin/ref_app.hex ./bin/ref_app.s19 ./bin/ref_app.map
        working-directory: ./ref_app/
